// Note that when importing our own components, their location must be given in relation to the importing file:
import Note from './components/Note';
// the period . in the beginning refers to the current directory, 
// so the module's location is a file called Note.jsx in the components sub-directory of the current directory.
// The filename extension .jsx can be omitted.

const Course = ({ course }) => (
  <div>
    <Header course={course} />
  </div>
)

const Header = ({ course }) => (<h1>{course}</h1>)

const App = ({ notes }) => {
  // Warning: Each child in a list should have a unique "key" prop.
  // React uses the key attributes of objects in an array to determine how to update the view generated by a component when the component is re-rendered. 
  // Using array indexes as keys is NOT recommended: notes.map((note, i) => <li key={i}></li>)

  const course = {
    name: "Information Systems",
    id: "cs101"
  };

  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note =>
          //<li key={note.id}>{note.content}</li>
          <Note key={note.id} note={note} />
        )}
      </ul>

      <Course course={course.name} />
    </div>
  )
}

// If you have any other components or parts of the application where you're rendering course or similar objects, ensure you're not passing the whole object to be rendered directly in the JSX.
// <Course course={course} /> will cause error
//Uncaught Error: Objects are not valid as a React child (found: object with keys {name, id}). If you meant to render a collection of children, use an array instead.

export default App
